
import React from 'react';
import { Navbar } from '../components/Navbar';
import { ViewState } from '../types';
import { AlertTriangle } from 'lucide-react';

interface TermsProps {
  onNavigate: (view: ViewState) => void;
}

export const Terms: React.FC<TermsProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-zinc-50/50 relative">
      <Navbar currentView="terms" onNavigate={onNavigate} />
      
      <main className="max-w-2xl mx-auto px-4 py-16 sm:px-6 relative z-10">
        <div className="
          bg-white/70 backdrop-blur-xl 
          border border-white/50 
          shadow-sm rounded-xl p-8 md:p-12
        ">
          <article className="prose prose-zinc max-w-none prose-headings:tracking-tight prose-headings:font-semibold prose-a:text-chef-green">
            <h1>Terms of Service</h1>
            <p className="lead text-zinc-600">
              By using ChefMate, you agree to the following terms. Please read them carefully.
            </p>

            {/* Critical AI Disclaimer */}
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 my-8 not-prose">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h3 className="text-amber-900 font-bold text-lg mb-2">AI Disclaimer & Medical Warning</h3>
                  <p className="text-amber-800 text-sm leading-relaxed">
                    ChefMate is an Artificial Intelligence assistant, <strong>not a nutritionist, dietician, or medical professional.</strong> All recipes, meal plans, and nutritional information are generated by AI and are for informational purposes only.
                    <br /><br />
                    <strong>You are responsible for verifying all ingredients for allergies, intolerances, or dietary restrictions before cooking or consuming any meal.</strong> ChefMate cannot guarantee that generated recipes are free from allergens.
                  </p>
                </div>
              </div>
            </div>

            <h3>1. Subscription Terms</h3>
            <p>
              <strong>Billing Cycle:</strong> Subscriptions (e.g., "Planner Pro") are billed on a monthly basis. Your plan will automatically renew at the end of each billing cycle unless you cancel it at least 24 hours before the renewal date.
            </p>
            <p>
              <strong>Cancellation & Refunds:</strong> You may cancel your subscription at any time via the Settings page. Cancellation takes effect at the end of the current billing period. <strong>We do not offer refunds for partial months or unused service time.</strong>
            </p>

            <h3>2. Usage Rights</h3>
            <p>
              <strong>Your Content:</strong> You retain ownership of any personal data you input into ChefMate.
            </p>
            <p>
              <strong>Generated Content:</strong> You own the recipes generated for you. However, by using the service, you grant ChefMate a worldwide, non-exclusive, royalty-free license to store, display, and reproduce this generated content for the purpose of operating and improving the service.
            </p>

            <h3>3. Acceptable Use Policy</h3>
            <p>
              You agree not to misuse the ChefMate services. This includes:
            </p>
            <ul>
                <li>Attempting to bypass API limits or reverse-engineer the application.</li>
                <li>Using the service to generate harmful, illegal, or abusive content.</li>
                <li>Sharing your account credentials with others to avoid paying for multiple seats.</li>
            </ul>

            <h3>4. Termination</h3>
            <p>
              We reserve the right to suspend or terminate your account immediately, without prior notice or liability, if you breach these Terms. Upon termination, your right to use the Service will immediately cease.
            </p>

            <h3>5. Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by law, ChefMate AG shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, or goodwill, resulting from your access to or use of or inability to access or use the service.
            </p>

            <hr className="border-zinc-200/60 my-8" />
            
            <p className="text-sm text-zinc-500">
                Last Updated: May 20, 2024
            </p>
          </article>
        </div>
      </main>
    </div>
  );
};
